#!/usr/bin/env node
// extract-harness.mjs — 이 레포의 에이전트 구성(스킬·커맨드·서브에이전트·훅·규칙·그래프)을 인벤토리로 추출한다.
//
// READ ONLY: 레포의 기존 파일을 절대 수정하지 않는다. 쓰기는 docs/reference/ 산출물뿐이다.
// 추론 금지: 선언되지 않은 필드는 null 로 둔다. 값을 지어내지 않는다.

import { readFileSync, readdirSync, statSync, existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join, relative, dirname, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT_DIR = join(ROOT, "docs", "reference");
const BANNER = "Generated by scripts/extract-harness.mjs. Do not edit by hand.";

const rel = (p) => relative(ROOT, p).split(sep).join("/");
const readIf = (p) => (existsSync(p) ? readFileSync(p, "utf-8") : null);
const lineCount = (t) => (t === null ? null : t.split(/\r?\n/).length);

function listFiles(dir, filter) {
  if (!existsSync(dir)) return [];
  const out = [];
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    if (statSync(full).isDirectory()) out.push(...listFiles(full, filter));
    else if (filter(full)) out.push(full);
  }
  return out.sort();
}

// ── 프론트매터 (YAML 부분집합: key: value / key: 뒤 "- item" 목록) ──
function parseFrontmatter(text) {
  const lines = text.split(/\r?\n/);
  if (lines[0]?.trim() !== "---") return { data: null, bodyStart: 0 };
  const end = lines.indexOf("---", 1);
  if (end === -1) return { data: null, bodyStart: 0 };
  const data = {};
  let key = null;
  for (const raw of lines.slice(1, end)) {
    if (!raw.trim()) continue;
    const kv = raw.match(/^([A-Za-z][\w-]*):\s*(.*)$/);
    const item = raw.match(/^\s*-\s+(.*)$/);
    if (kv) {
      key = kv[1];
      const v = kv[2].trim();
      data[key] = v === "" ? [] : unquote(v);
    } else if (item && key && Array.isArray(data[key])) {
      data[key].push(unquote(item[1].trim()));
    } else if (key && typeof data[key] === "string") {
      data[key] += " " + raw.trim(); // 접힌 여러 줄 값
    }
  }
  return { data, bodyStart: end + 1 };
}
const unquote = (s) => s.replace(/^["'](.*)["']$/, "$1");
const get = (d, k) => (d && d[k] !== undefined ? d[k] : null);

// ── 본문이 가리키는 파일 경로 수집 (레포 접두사로 시작하는 것만) ──
const PATH_RE =
  /(?:^|[\s`("'[|>])((?:\.claude|docs|gates|scripts|projects|src|supabase)\/[^\s`"'()[\]|,·]+|graph\.mjs|CLAUDE\.md|ACTIVE)/g;
function referencedPaths(body) {
  const found = new Map();
  for (const m of body.matchAll(PATH_RE)) {
    // 뒤에 붙은 구두점과 한글 조사("…design-rules.md를")를 떼어낸다. 레포 경로엔 한글이 없다.
    let p = m[1].replace(/[.,:;)`\]]+$/, "").replace(/[가-힣]+$/, "").replace(/[.,:;)`\]]+$/, "");
    if (!p || found.has(p)) continue;
    const dynamic = /[*<>$]/.test(p); // 글롭·<이름>·$변수 자리표시자 → 존재 판정 불가
    found.set(p, { path: p, dynamic, exists: dynamic ? null : existsSync(join(ROOT, p)) });
  }
  return [...found.values()];
}

// ── 1. 스킬 ──
const SKILLS_DIR = join(ROOT, ".claude", "skills");
const skills = listFiles(SKILLS_DIR, (f) => f.endsWith("SKILL.md")).map((file) => {
  const text = readFileSync(file, "utf-8");
  const { data, bodyStart } = parseFrontmatter(text);
  const body = text.split(/\r?\n/).slice(bodyStart).join("\n");
  const description = get(data, "description");
  return {
    name: get(data, "name"),
    description,
    description_word_count: description === null ? null : description.trim().split(/\s+/).length,
    "allowed-tools": get(data, "allowed-tools"),
    "disable-model-invocation": get(data, "disable-model-invocation"),
    "argument-hint": get(data, "argument-hint"),
    path: rel(file),
    line_count: lineCount(text),
    referenced_paths: referencedPaths(body),
  };
});

// ── 2. 커맨드 ──
const COMMANDS_DIR = join(ROOT, ".claude", "commands");
const commands_dir_exists = existsSync(COMMANDS_DIR);
const commands = listFiles(COMMANDS_DIR, (f) => f.endsWith(".md")).map((file) => {
  const text = readFileSync(file, "utf-8");
  const { data, bodyStart } = parseFrontmatter(text);
  const body = text.split(/\r?\n/).slice(bodyStart).join("\n");
  const names = new Set([...skills.map((s) => s.name), ...[]].filter(Boolean));
  return {
    name: get(data, "name"),
    description: get(data, "description"),
    path: rel(file),
    line_count: lineCount(text),
    referenced_skills_or_agents: [...names].filter((n) => new RegExp(`\\b${n}\\b`).test(body)),
    referenced_paths: referencedPaths(body),
  };
});

// ── 3. 서브에이전트 ──
const AGENTS_DIR = join(ROOT, ".claude", "agents");
const subagents = listFiles(AGENTS_DIR, (f) => f.endsWith(".md")).map((file) => {
  const text = readFileSync(file, "utf-8");
  const { data, bodyStart } = parseFrontmatter(text);
  const body = text.split(/\r?\n/).slice(bodyStart).join("\n");
  const tools = get(data, "tools");
  return {
    name: get(data, "name"),
    description: get(data, "description"),
    tools: tools === null ? null : String(tools).split(",").map((t) => t.trim()).filter(Boolean),
    // 이 하네스에는 "쓰기 허용 파일"을 선언하는 필드가 없다 → 선언이 없으면 null (추론하지 않음)
    writable_files_declared: get(data, "writable-files"),
    path: rel(file),
    line_count: lineCount(text),
    referenced_paths: referencedPaths(body),
  };
});

// ── 4. 훅 ──
const SETTINGS_FILES = [
  join(ROOT, ".claude", "settings.json"),
  join(ROOT, ".claude", "settings.local.json"),
].filter(existsSync);
const hooks = [];
for (const file of SETTINGS_FILES) {
  const cfg = JSON.parse(readFileSync(file, "utf-8"));
  for (const [event, groups] of Object.entries(cfg.hooks ?? {})) {
    for (const group of groups) {
      for (const h of group.hooks ?? []) {
        const command = h.command ?? null;
        const m = command?.match(/node\s+(?:"([^"]+)"|(\S+))/);
        const target = m ? (m[1] ?? m[2]) : null;
        hooks.push({
          event,
          matcher: group.matcher ?? null,
          type: h.type ?? null,
          command,
          target_file: target,
          target_exists: target === null ? null : existsSync(join(ROOT, target)),
          configured_in: rel(file),
        });
      }
    }
  }
}

// ── 5. 규칙 ──
const RULES_DIR = join(ROOT, ".claude", "rules");
const rules = listFiles(RULES_DIR, (f) => f.endsWith(".md")).map((file) => {
  const text = readFileSync(file, "utf-8");
  const { data, bodyStart } = parseFrontmatter(text);
  const body = text.split(/\r?\n/).slice(bodyStart).join("\n");
  const paths = get(data, "paths");
  return {
    path: rel(file),
    path_scope: paths === null ? null : Array.isArray(paths) ? paths : [paths],
    // paths 프론트매터 = 자동 로드 조건. 없으면 선언된 로드 조건 없음 → null
    load_condition: paths === null ? null : "path-match",
    bytes: statSync(file).size,
    line_count: lineCount(text),
    referenced_paths: referencedPaths(body),
  };
});

// ── 6. 그래프 ──
const GRAPH_FILE = join(ROOT, "graph.mjs");
const graphMod = await import(pathToFileURL(GRAPH_FILE).href);
const GRAPH = graphMod.GRAPH;
const cleanWhenKinds = (cw) => (cw ? Object.keys(cw) : null);
const graphNodes = Object.entries(GRAPH).map(([name, n]) => ({
  name,
  depends_on: n.depends_on ?? null,
  produces: n.produces ?? null,
  clean_when: n.clean_when ?? null,
  clean_when_kinds: cleanWhenKinds(n.clean_when),
  parallel_children: n.parallel
    ? Object.entries(n.parallel).map(([cname, c]) => ({
        name: cname,
        produces: c.produces ?? null,
        clean_when: c.clean_when ?? null,
        clean_when_kinds: cleanWhenKinds(c.clean_when),
      }))
    : null,
  on_fail_diagnose: n.on_fail_diagnose ?? null,
  extra_fields: Object.keys(n).filter(
    (k) => !["depends_on", "produces", "clean_when", "parallel", "on_fail_diagnose"].includes(k)
  ),
}));
const graph = {
  file: rel(GRAPH_FILE),
  exports: Object.keys(graphMod),
  line_count: lineCount(readFileSync(GRAPH_FILE, "utf-8")),
  node_count: graphNodes.length,
  nodes: graphNodes,
  edge_kinds: [
    ...new Set(
      graphNodes.flatMap((n) => [
        ...(n.depends_on?.length ? ["depends_on"] : []),
        ...(n.parallel_children ? ["parallel"] : []),
      ])
    ),
  ],
  clean_when_kinds_used: [
    ...new Set(
      graphNodes.flatMap((n) => [
        ...(n.clean_when_kinds ?? []),
        ...(n.parallel_children?.flatMap((c) => c.clean_when_kinds ?? []) ?? []),
      ])
    ),
  ],
  // graph.mjs 자체에 전파 로직은 없다(순수 리터럴). 아래는 파일에서 읽어낸 사실만.
  propagation: {
    declared_in_graph_mjs: false,
    routing_fields_present: graphNodes.some((n) => n.extra_fields.some((f) => /route|next|goto/i.test(f))),
    implementation_files: ["gates/propagate.mjs", "gates/graph-stop.mjs"].filter((p) =>
      existsSync(join(ROOT, p))
    ),
    rules_found_in_implementation: (() => {
      const src = readIf(join(ROOT, "gates", "propagate.mjs"));
      if (src === null) return null;
      return {
        exports: [...src.matchAll(/export\s+function\s+(\w+)/g)].map((m) => m[1]),
      };
    })(),
  },
};

// ── 산출 ──
const inventory = {
  generated_by: "scripts/extract-harness.mjs",
  root: ".",
  skills,
  commands: { dir: rel(COMMANDS_DIR), dir_exists: commands_dir_exists, items: commands },
  subagents,
  hooks,
  rules,
  graph,
};

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(join(OUT_DIR, "inventory.json"), JSON.stringify(inventory, null, 2) + "\n", "utf-8");

const nn = (v) => (v === null || v === undefined ? "null" : Array.isArray(v) ? (v.length ? v.join(", ") : "(empty)") : String(v));
const refList = (refs) =>
  refs.length === 0
    ? "- referenced_paths: (none)\n"
    : "- referenced_paths:\n" +
      refs.map((r) => `  - \`${r.path}\` — exists: ${r.exists === null ? "null (glob/placeholder)" : r.exists}\n`).join("");

function md(name, body) {
  writeFileSync(join(OUT_DIR, name), `${BANNER}\n\n${body}`, "utf-8");
}

md(
  "skills.md",
  `# Skills\n\ncount: ${skills.length}\n\n` +
    skills
      .map(
        (s) =>
          `## ${nn(s.name)}\n\n- path: \`${s.path}\`\n- line_count: ${nn(s.line_count)}\n` +
          `- allowed-tools: ${nn(s["allowed-tools"])}\n- disable-model-invocation: ${nn(s["disable-model-invocation"])}\n` +
          `- argument-hint: ${nn(s["argument-hint"])}\n- description_word_count: ${nn(s.description_word_count)}\n` +
          `- description (verbatim):\n\n> ${nn(s.description)}\n\n${refList(s.referenced_paths)}`
      )
      .join("\n")
);

md(
  "commands.md",
  `# Commands\n\n- dir: \`${rel(COMMANDS_DIR)}\`\n- dir_exists: ${commands_dir_exists}\n- count: ${commands.length}\n` +
    (commands.length === 0
      ? "\n(no command files found)\n"
      : "\n" +
        commands
          .map(
            (c) =>
              `## ${nn(c.name)}\n\n- path: \`${c.path}\`\n- description: ${nn(c.description)}\n` +
              `- referenced_skills_or_agents: ${nn(c.referenced_skills_or_agents)}\n${refList(c.referenced_paths)}`
          )
          .join("\n"))
);

md(
  "subagents.md",
  `# Subagents\n\ncount: ${subagents.length}\n\n` +
    subagents
      .map(
        (a) =>
          `## ${nn(a.name)}\n\n- path: \`${a.path}\`\n- line_count: ${nn(a.line_count)}\n- tools: ${nn(a.tools)}\n` +
          `- writable_files_declared: ${nn(a.writable_files_declared)}\n- description (verbatim):\n\n> ${nn(a.description)}\n\n${refList(a.referenced_paths)}`
      )
      .join("\n")
);

md(
  "hooks.md",
  `# Hooks\n\ncount: ${hooks.length}\n\n| event | matcher | type | command | target_file | target_exists | configured_in |\n|---|---|---|---|---|---|---|\n` +
    hooks
      .map(
        (h) =>
          `| ${h.event} | ${h.matcher === null ? "null" : "`" + h.matcher + "`"} | ${nn(h.type)} | \`${nn(h.command)}\` | ${h.target_file === null ? "null" : "`" + h.target_file + "`"} | ${nn(h.target_exists)} | \`${h.configured_in}\` |`
      )
      .join("\n") +
    "\n"
);

md(
  "rules.md",
  `# Rules\n\ncount: ${rules.length}\n\n` +
    rules
      .map(
        (r) =>
          `## ${r.path}\n\n- load_condition: ${nn(r.load_condition)}\n- path_scope: ${r.path_scope === null ? "null" : "\n" + r.path_scope.map((p) => `  - \`${p}\``).join("\n")}\n` +
          `- bytes: ${nn(r.bytes)}\n- line_count: ${nn(r.line_count)}\n${refList(r.referenced_paths)}`
      )
      .join("\n")
);

md(
  "graph.md",
  `# Graph\n\n- file: \`${graph.file}\`\n- exports: ${nn(graph.exports)}\n- node_count: ${graph.node_count}\n` +
    `- edge_kinds: ${nn(graph.edge_kinds)}\n- clean_when_kinds_used: ${nn(graph.clean_when_kinds_used)}\n` +
    `- propagation.declared_in_graph_mjs: ${graph.propagation.declared_in_graph_mjs}\n` +
    `- propagation.routing_fields_present: ${graph.propagation.routing_fields_present}\n` +
    `- propagation.implementation_files: ${nn(graph.propagation.implementation_files)}\n` +
    `- propagation.rules_found_in_implementation.exports: ${nn(graph.propagation.rules_found_in_implementation?.exports ?? null)}\n\n` +
    `## Nodes\n\n| node | depends_on | produces | clean_when kinds | parallel children | on_fail_diagnose |\n|---|---|---|---|---|---|\n` +
    graphNodes
      .map(
        (n) =>
          `| ${n.name} | ${nn(n.depends_on)} | ${n.produces === null ? "null" : n.produces.map((p) => "`" + p + "`").join(", ")} | ${nn(n.clean_when_kinds)} | ${n.parallel_children === null ? "null" : n.parallel_children.map((c) => c.name).join(", ")} | ${nn(n.on_fail_diagnose)} |`
      )
      .join("\n") +
    "\n\n## Parallel children\n\n" +
    (graphNodes.filter((n) => n.parallel_children).length === 0
      ? "(none)\n"
      : graphNodes
          .filter((n) => n.parallel_children)
          .flatMap((n) =>
            n.parallel_children.map(
              (c) =>
                `- ${n.name} / ${c.name} — produces: ${c.produces === null ? "null" : c.produces.map((p) => "`" + p + "`").join(", ")} — clean_when kinds: ${nn(c.clean_when_kinds)}`
            )
          )
          .join("\n") + "\n")
);

console.log(
  `wrote ${rel(join(OUT_DIR, "inventory.json"))} + skills/commands/subagents/hooks/rules/graph .md\n` +
    `skills=${skills.length} commands=${commands.length} subagents=${subagents.length} hooks=${hooks.length} rules=${rules.length} graph_nodes=${graph.node_count}`
);
